Cardproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('card.urls', namespace='card'))
]

card/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'card'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('cards/', views.profile_cards, name='cards'),
    path('cards/new_card', views.new_card, name='new_card'),
    path('cards/delete_card/<int:id>', views.delete_card, name='delete_card'),
    path('cards/deactivate_card/<int:id>', views.deactivate_card, name='deactivate_card'),
    path('cards/activate_card/<int:id>', views.activate_card, name='activate_card'),
    # path('login/', views.user_login, name='login')
]

card/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


SEX_CHOICES = [
    ('M', 'M'),
    ('F', 'F')
]


class Profile(AbstractUser):
    sex = models.CharField(max_length=4, default=SEX_CHOICES[1], choices=SEX_CHOICES, db_index=True, verbose_name='Пол')

    class Meta(AbstractUser.Meta):
        pass


class Card(models.Model):
    status_choices = [
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
        ('Prosrochena', 'Prosrochena')
    ]
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='cards')
    series = models.PositiveSmallIntegerField(verbose_name='серия')
    number = models.BigIntegerField(verbose_name='номер')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='создана')
    ended_at = models.DateTimeField(verbose_name='срок истекает')
    status = models.CharField(max_length=20, default=status_choices[0], choices=status_choices, verbose_name='статус')

    class Meta:
        ordering = ('profile',)
        verbose_name = 'karta'
        verbose_name_plural = 'karti'

    def __str__(self):
        return f'{self.series} {self.number}'

card/forms.py
from .models import Profile
from django import forms


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    rep_password = forms.CharField(label='repeat password', widget=forms.PasswordInput)

    class Meta:
        model = Profile
        fields = ['username', 'first_name', 'last_name', 'email', 'sex']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['rep_password']:
            raise forms.ValidationError('Passwords mismatch')
        return cd['rep_password']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

card/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Card, Profile
from .forms import RegistrationForm, LoginForm
import random
from django.views.generic.edit import DeleteView
from datetime import datetime, timedelta


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            if form.cleaned_data['password'] == form.cleaned_data['rep_password']:
                new_user.set_password(form.cleaned_data['password'])
                new_user.save()
                return render(request, 'registration/registration_done.html', {'form': form})
            else:
                return render(request, 'registration/registration.html', {'form': form})
    else:
        form = RegistrationForm()
        return render(request, 'registration/registration.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data()
            user = authenticate(request, username=cd['username'], password=cd['password'])
            login(request, user)
    else:
        login_form = LoginForm()
        return render(request, 'register/login.html', {'login_form': login_form})


@login_required
def profile_cards(request):
    cards = Card.objects.filter(profile=request.user)
    paginator = Paginator(cards, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'card/cards.html', {'cards': cards, 'page_obj': page_obj})


@login_required
def new_card(request):
    card = Card.objects.create(profile=request.user,
                               series=random.randint(1000, 9999),
                               number=random.randint(100000000000, 999999999999),
                               ended_at=datetime.now()+timedelta(days=365),
                               status='Active')
    return HttpResponse('Yo, U have a new card, check your cards, for more info')


@login_required
def delete_card(request, id):
    cards = Card.objects.filter(profile=request.user)
    card = Card.objects.get(id=id).delete()
    return render(request, 'card/cards.html', {'card': card, 'cards': cards})


@login_required
def deactivate_card(request, id):
    cards = Card.objects.filter(profile=request.user)
    card = Card.objects.filter(id=id).update(status=Card.status_choices[1][1])
    return render(request, 'card/cards.html', {'card': card, 'cards': cards})


@login_required
def activate_card(request, id):
    cards = Card.objects.filter(profile=request.user)
    card = Card.objects.filter(id=id).update(status=Card.status_choices[0][1])
    return render(request, 'card/cards.html', {'card': card, 'cards': cards})


def profile(request):
    return render(request, 'accounts/profile.html')

card/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<span>
    {% if request.user.is_authenticated %}
        Hello, {{ request.user.first_name }} &nbsp; &nbsp; &nbsp; &nbsp;
        <a href="{% url 'card:logout' %}"><button>Logout</button></a> &nbsp; &nbsp; &nbsp; &nbsp;
        <a href="{% url 'card:cards' %}"><button>My cards</button></a>
        {% else %}
        <a href="{% url 'card:login' %}"><button>Login</button></a>&nbsp; &nbsp;
        <a href="{% url 'card:register' %}"><button>Registration</button></a>&nbsp; &nbsp;
    {% endif %}
</span>
</body>
</html>

card/templates/card/cards.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<ul>
    <li>
        <a href="{% url 'card:new_card' %}"><button>New card</button></a>
    </li>
    <br>
    <li>
        <a href="#"><button>Delete card</button></a>
    </li>

</ul>
<body>
    <h1>YOUR CARDS:</h1>
    {% if request.user.is_authenticated %}
    {% for card in page_obj%}
        <h2>Карта: </h2>
    <ul>
        <li>Серия: {{card.series}}</li>
        <li>Номер: {{card.number}}</li>
        <li>Срок истекает: {{card.ended_at}}</li>
        <li>Статус карты: {{card.status}}</li>
        <li>
            {% csrf_token %}
            <a href="{% url 'card:delete_card' id=card.id %} "><button>Удалить карту</button></a>
        </li>
        <li>
            {% csrf_token %}
            {% if card.status == "Active" %}
            <a href="{% url 'card:deactivate_card' id=card.id %} ">
                <button>Деактивировать карту</button>
            </a>
                {%else%}
            <a href="{% url 'card:activate_card' id=card.id %} ">
                <button>Активировать карту</button>
            </a>
                {%endif%}
        </li>
        </ul>
    <hr>
    {% endfor %}
    {%endif%}
{%if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}
<span>
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
</span>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
</body>
</html>